name: Test

on: [ pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - run: npm ci
      - run: |
          npm run test -- --coverage --no-color 2>&1 | sed '0,/^-\{2,\}/s/^-\{2,\}.*//' | head -n-1 | tee $GITHUB_STEP_SUMMARY
          exit_code=${PIPESTATUS[0]}
          exit $exit_code
